### ISSUE TITLE
基本雛形デザイン確認

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#1]
SP（修正） 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/
PC（修正および作成） 　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/
→構築が月曜日から進んでいく関係で、ここのお返事のみ先にいただけますと幸いです。

**Comment by niizato** [comment]
どちらも確認終わりました。PC版のXDに修正依頼を書き込んでいます。よろしくお願いします；

**Comment by SuzukaKuwabara** [comment]
@niizato 
確認中かと思いますが、１点お知らせです。

テキストの下線が途切れ途切れになっていますが、これはXDで作るとこうなってしまうだけで、実際に構築するとちゃんとした下線になりますのでご了承くださいm(_ _)m

<img width="330" alt="スクリーンショット 2023-09-04 11 41 39" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/3deabbbd-f094-43e1-9792-a448fe174929">

**Comment by SuzukaKuwabara** [comment]
@niizato 
修正が完了しました。

PC  　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/
→指示通りの修正をしています。XDのピンが若干ズレてますのでご注意ください。
メニューの出方は、参考サイトありがとうございます！

SP  　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/
→フッター上の「この特集のタグ」を修正しています。

あとテーブルの件が決まれば確定して開発に回します。

**Comment by niizato** [comment]
@SuzukaKuwabara 

ありがとうございます。大丈夫です！

**Comment by SuzukaKuwabara** [comment]
@niizato 
PCのボトムナビゲーションについて確認です。

今気づいたのですが、、
「マイページ」のナビが、PCにはないようですがこれはどうしましょうか？

スマホではマイページがある
![SP](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/7d098402-2825-42c0-9f66-09b1c4c4bbdf)

PCではない？
![PC](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/fdad9141-b02d-4a95-9913-5eeb85d552e3)

**Comment by niizato** [comment]
@SuzukaKuwabara 

PCではナビが目立つのでマイページはいらないかなーと思って外してました。
あったほうがいいですか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
項目が統一されていないとなんとなく違和感があるというだけですね。

いま、改めて考えていて判明したことがあるのですが、
ボトムナビゲーションのスマホの方で「マイページ」のリンクがあるのですが、これ、リンクできないかもしれません。

マイページのURLはおそらく動的に作成されているようで、makeshopのサイト内からしかリンクできないのかも・・・？

ちょっと、こちら、調査します。

もしリンクができないのであれば、PCに合わせてスマホも４つのメニューにしないといけないかもですね；

**Comment by SuzukaKuwabara** [comment]
@niizato 
ボトムナビゲーションとは別の件で確認です。

### 特集記事のページの上部の部分について
![特集記事のページ上部について](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/048612a0-1d06-403a-925c-cf65ddeb40d8)

こちらは、⬆︎の画像で示したパーツで構成されますが、

- パーツの順番は変えることができない
- 全てグレーの色の枠内に収まる形になる（白にしたり色を変えたりできない）

という仕様で作ります。
背景のグレーの色を変えられるようにすると
ちょっと複雑なコードになってしまうため
こちらでご了承いただきたいのですが、問題ないでしょうか？

**Comment by niizato** [comment]
> @niizato 項目が統一されていないとなんとなく違和感があるというだけですね。
> 
> いま、改めて考えていて判明したことがあるのですが、 ボトムナビゲーションのスマホの方で「マイページ」のリンクがあるのですが、これ、リンクできないかもしれません。
> 
> マイページのURLはおそらく動的に作成されているようで、makeshopのサイト内からしかリンクできないのかも・・・？
> 
> ちょっと、こちら、調査します。
> 
> もしリンクができないのであれば、PCに合わせてスマホも４つのメニューにしないといけないかもですね；

もしマイページができない場合、「新商品」か、マルヒロでは閲覧の多かった「すべての商品」に変更するかもしれません。
もしくは、リンクの調査せずにそちらに変更しても大丈夫です。

**Comment by niizato** [comment]
> @niizato ボトムナビゲーションとは別の件で確認です。
> 
> ### 特集記事のページの上部の部分について
> ![特集記事のページ上部について](https://user-images.githubusercontent.com/109566570/266170759-048612a0-1d06-403a-925c-cf65ddeb40d8.png)
> 
> こちらは、⬆︎の画像で示したパーツで構成されますが、
> 
> * パーツの順番は変えることができない
> * 全てグレーの色の枠内に収まる形になる（白にしたり色を変えたりできない）
> 
> という仕様で作ります。 背景のグレーの色を変えられるようにすると ちょっと複雑なコードになってしまうため こちらでご了承いただきたいのですが、問題ないでしょうか？


@SuzukaKuwabara 
シェアボタンと日付を入れたくない記事の場合、「入れない」選択もできますか？

**Comment by SuzukaKuwabara** [comment]
@niizato 

>もしマイページができない場合、「新商品」か、マルヒロでは閲覧の多かった「すべての商品」に変更するかもしれません。もしくは、リンクの調査せずにそちらに変更しても大丈夫です。

→軽く調査した感じだと、
「マイページ、お気に入り一覧ページに　ECサイト以外からリンクさせる」はできなさそうです。
makeshopさんに他にも聞きたいことがあるので、ちょっと聞いてみようかなとは思っています。
いずれにしても「別途費用」とか言われるかもなので、あまり期待しないでお待ちください。

**Comment by SuzukaKuwabara** [comment]
@niizato 

>シェアボタンと日付を入れたくない記事の場合、「入れない」選択もできますか？

はい！それは大丈夫です！
というか、全てのパーツがON/OFFはできるようにしようかなと思っています。

特集商品へのリンクボタンとかは、いらないページとかも出てくるでしょうし＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 
### アンカーリンク用のIDについて

こちらの、「見出し・画像・テキスト」にアンカーリンクを付ける機能、
新しいWordpressでも実装しますが、画像のセクションにも必要でしょうか？
ページ内リンクさせることが結構ありますか・・・・？

<img width="993" alt="スクリーンショット 2023-09-07 14 40 29" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/176c6440-ca77-49d7-b316-615340977929">

できる限りシンプルに作りたいので、画像のセクションでは不要であれば、カットしようかなぁと思っていたのdですが、どうでしょうか？

**Comment by niizato** [comment]
> @niizato
> 
> > シェアボタンと日付を入れたくない記事の場合、「入れない」選択もできますか？
> 
> はい！それは大丈夫です！ というか、全てのパーツがON/OFFはできるようにしようかなと思っています。
> 
> 特集商品へのリンクボタンとかは、いらないページとかも出てくるでしょうし＾＾

@SuzukaKuwabara 

それであれば、以下のような仕様で進めていただいて大丈夫です！

▼
パーツの順番は変えることができない
全てグレーの色の枠内に収まる形になる（白にしたり色を変えたりできない）
という仕様で作ります。
背景のグレーの色を変えられるようにすると
ちょっと複雑なコードになってしまうため
こちらでご了承いただきたいのですが、問題ないでしょうか？

**Comment by niizato** [comment]
> @niizato
> 
> ### アンカーリンク用のIDについて
> こちらの、「見出し・画像・テキスト」にアンカーリンクを付ける機能、 新しいWordpressでも実装しますが、画像のセクションにも必要でしょうか？ ページ内リンクさせることが結構ありますか・・・・？
> 
> <img alt="スクリーンショット 2023-09-07 14 40 29" width="993" src="https://user-images.githubusercontent.com/109566570/266215812-176c6440-ca77-49d7-b316-615340977929.png">
> できる限りシンプルに作りたいので、画像のセクションでは不要であれば、カットしようかなぁと思っていたのdですが、どうでしょうか？

画像のセクションへのアンカーリンクは必要ないです。おそらく見出しなどにリンクさせることが多いと思うので。

@ETOmaruhiro 
どうですか？

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara @niizato 
画像のセクションにはなくても大丈夫そうです！

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 

ありがとうございます。
では「見出し」と「テキスト」にIDの機能をつけておきますね！

**Comment by SuzukaKuwabara** [comment]
@niizato 

### ボトムナビゲーションの件

今回作っているWordPressサイトから「マイページ」と「お気に入り商品一覧」へリンクさせるのが可能かどうかという件についてですが、makeさんに相談しましたが、やはり難しそうです。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/3d3ec1c6-bf6d-4bf7-9010-06961f23825b" width="250px">

以前、
>もしマイページができない場合、「新商品」か、マルヒロでは閲覧の多かった「すべての商品」に変更するかもしれません。もしくは、リンクの調査せずにそちらに変更しても大丈夫です。

というふうにご回答いただいていましたが、
改めてメニューをどうするかご検討いただき、データご準備下さいm(_ _)m

全ページに関わる部分ですので今週中くらいにいただけるととても助かります。
間に合わなさそうであれば、ご連絡ください。

**Comment by niizato** [comment]
@SuzukaKuwabara 

ボトムナビゲーションの件は今日中に返信できるようにします！
トップページのヘッダーは検索とハンバーガーメニューだけのデザインにしていたので、ヘッダーに「マイページ」と「お気に入り商品一覧を」表示させるのは大丈夫でしょうか？

**Comment by niizato** [comment]
<img width="434" alt="スクリーンショット 2023-09-11 10 15 41" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/707dd3e4-e64d-49f4-9cf6-6b3a279ed2b8">

**Comment by SuzukaKuwabara** [comment]
@niizato 

はい、ストアのトップのことですよね。

こちらはmakeshopの中に作るページなので、
・マイページ
・ログイン/ログアウト
・お気に入り商品一覧
などのボタンを作って大丈夫です！！

（むしろ無いと困るものなので、入れてください＾＾）

**Comment by niizato** [comment]
@SuzukaKuwabara 

ボトムナビゲーションとPCのフォローティングボタンの修正をしました。
https://drive.google.com/file/d/1GBui7I7TxnOe2TUr9zqqnV29MtjIEVGn/view?usp=sharing

**Comment by niizato** [comment]
<img width="1213" alt="スクリーンショット 2023-09-11 14 15 11" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/3b1dac68-f1bb-449c-ab7b-b0d1c5bf07fd">

・「MY PAGE」「FAVORITES」削除
・「ALL ITEM」「PICK UP」追加
※pickupは新しく特集ページを作ります。

**Comment by SuzukaKuwabara** [comment]
@niizato 
早速ありがとうございます！
こちらで構築進めさせていただきますね＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 

### 同じカテゴリの商品の仕様について
記事の下に置く《同じカテゴリの商品》についてです。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/da9dfce7-9c28-40eb-99a1-0adbadc4f33f" width="250px">
プレビューで確認(SP)→  https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/
プレビューで確認(PC)→  https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/

こちら、仕組みとしては「**商品セットに登録した商品リストを呼び出して**表示する」
という仕様になります。

ただ、呼び出したい商品セットに50個商品が登録されていたばあい、
自動で全件表示させるとページが重くなってしまうので、
できれば**表示件数に制限を設けたい**です。

例）
①PC、SPともに最大６件表示
②PCは8件、SPは6件表示
③マルヒロさん側で調整するので全件表示で良い
など。

いかがでしょうか？

なお、今のサイトの「おすすめ商品」のようにループする形のスライダーを想定していますので、表示する商品点数が少なくても「少ないなぁ」って感じることはないかなと思います。


ご検討くださいm(_ _)m

**Comment by niizato** [comment]
> @niizato
> 
> ### 同じカテゴリの商品の仕様について
> 記事の下に置く《同じカテゴリの商品》についてです。 <img alt="" width="250px" src="https://user-images.githubusercontent.com/109566570/267228230-da9dfce7-9c28-40eb-99a1-0adbadc4f33f.png"> プレビューで確認(SP)→ https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/ プレビューで確認(PC)→ https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/
> 
> こちら、仕組みとしては「**商品セットに登録した商品リストを呼び出して**表示する」 という仕様になります。
> 
> ただ、呼び出したい商品セットに50個商品が登録されていたばあい、 自動で全件表示させるとページが重くなってしまうので、 できれば**表示件数に制限を設けたい**です。
> 
> 例） ①PC、SPともに最大６件表示 ②PCは8件、SPは6件表示 ③マルヒロさん側で調整するので全件表示で良い など。
> 
> いかがでしょうか？
> 
> なお、今のサイトの「おすすめ商品」のようにループする形のスライダーを想定していますので、表示する商品点数が少なくても「少ないなぁ」って感じることはないかなと思います。
> 
> ご検討くださいm(_ _)m

@SuzukaKuwabara 

②PCは8件、SPは6件表示でお願いします！

**Comment by SuzukaKuwabara** [comment]
@niizato 

### スライダーについて
こちらの《スライダーのブロック》についてです。
<img width="300" alt="スクリーンショット 2023-09-12 15 55 08" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/716f2ad9-38ca-4cce-a316-863b6159f611">
<img width="300" alt="スクリーンショット 2023-09-12 15 55 08" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/a38f379c-e818-44a4-a94f-9b5470402b26">

こちら、「最後にMOREのカードをつけることもできる」という仕様だったのですが、
そうなるとPCのときこんな感じの位置についてしまい、不自然です。。
<img width="450" alt="" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/00f5ad4f-1fd3-4f6c-84d6-e31f5d56df62">

そのため、もっと見るリンクをつけたい際に、スライダーの下部に「もっと見る」というボタンを置いたらどうかなと思うのですが、いかがでしょうか？
<img width="300" alt="" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/d9c80e6b-a1fb-473d-89b5-86c0f19d12bd">
※もちろんリンクがないときは非表示です
※マルヒロさんの方でデザインしたボタンでもOKです。とりあえずで置いてます。

**Comment by niizato** [comment]
@SuzukaKuwabara 


スライダー下のボタン作成しました！
https://drive.google.com/file/d/1v_Uwedb6v93SOM13GWgcwBlM6fGDdqMJ/view?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！ではこちらで進めます。

**Comment by SuzukaKuwabara** [comment]
@niizato 

### ボトムナビゲーションのそれぞれのリンク先の確認

下記URLの確認と、PICKUPのURLが決まっていれば教えてください＾＾

HOME 　https://store.hasamiyaki.jp/
PICKUP　？
CATEGORY　https://store.hasamiyaki.jp/html/page66.html
CART　https://store.hasamiyaki.jp/shop/basket.html
ALL ITEM　https://store.hasamiyaki.jp/shopbrand/all

**Comment by niizato** [comment]
@SuzukaKuwabara 

ピックアップは、おすすめ商品のカテゴリーを作るのでこの後衞藤から連絡させます！
他のリンクは大丈夫です

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
おすすめ商品のリンクは下記URLでお願いいたします。
https://store.hasamiyaki.jp/shopbrand/pickup

**Comment by SuzukaKuwabara** [comment]
@niizato @ETOmaruhiro 
ありがとうございます＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 

### 検索のメニューについてご相談
ヘッダーメニューの「検索ボタン」のところについて相談です。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/fc2ffbfc-9b63-4c71-981e-6c2939ee4c23" width="250">

こちらはこのサイト（ 　https://ameiro-home.com/　 ）のように
**アイコンを押すとページは遷移せず、メニューとして開く**
という想定だと思います。プロトタイプもそのようにしています。

が、そうではなくて、これを
**アイコンを押すと、ページ遷移して⬇︎こちらのページが開く**
という仕様に変更させていただくことは可能でしょうか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/5a4884f1-3296-4ee8-a0f8-7d6ac450aa66" width="250">

というのも、

今回のサイト、全体的に「記事を読み込む」「商品を読みこむ」など、便利に使っていただくためにちょっとWordPressに複雑な動きをさせていたり、関連記事や関連商品を読み込む部分が非常に多く、記事ページが重くなってきています。そのため少しでも負担軽減のために、、、という意味合いです。

今回ご提案している仕様でひとまず構築してみて、
構築が終わってから（来週以降）、触ってみてから決定していただいても大丈夫です。

いかがでしょうか？

**Comment by niizato** [comment]
@SuzukaKuwabara 

ページが遷移する仕組みで大丈夫です！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ご理解いただきありがとうございますm(_ _)m
では一旦そちらで進めますね。

仕上がってから触ってみて、どうするか最終判断ください！

**Comment by SuzukaKuwabara** [comment]
@niizato 

### ボタンの仕様について

今、ボタンが数種類あると思いますが、こちらについて確認です。

一番右のボタンは、今いただいているデザインだと「記事上部のグレーの部分」でしか出てきません。
このボタンは、グレーの部分でしか使えない仕様でも大丈夫でしょうか？

デザインの統一感を守るためにも、なるべく選択肢が少ないほうがいいかなーと思うので、、いかがでしょうか？
![スクリーンショット 2023-09-20 17 21 43](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/54191aa7-dd6e-438a-b02f-7f7c19a45441)

グレーの部分ってここのことです⬇︎
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/98fa677a-8b4b-4611-bb15-e72f9f2cf28c" width="300">

**Comment by niizato** [comment]
@SuzukaKuwabara 

グレーの部分でしか使えない仕様でいいです！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！それで進めますね。

**Comment by SuzukaKuwabara** [comment]
@niizato 
### ページ名称について
- CREATOR’S  SELECT
- Magical Adventure
- ABOUT CREATOR
についてですが、

ハンバーガーメニューの中では
- クリエイターズセレクト
- マジカルアドベンチャー
- クリエイター紹介

と、日本語表記にしておいて良いですか？

**Comment by SuzukaKuwabara** [comment]
@niizato 

### CSVのことについて
Wordpressに読み込ませる商品情報のCSVの中に、どうしてもラッピング商品も含まれてしまうので、自動的に読み込ませないようにしたいと思います。

それでお伺いしたいのですが
ラッピング商品は
・商品名の冒頭に必ず「ラッピング」が含まれる
かつ
・メインカテゴリが「ラッピング商品」になっている
という認識でよかったでしょうか？

**Comment by niizato** [comment]
@SuzukaKuwabara 
上記認識で問題ありませんが、上記2件は手動で変更可能なので独自商品コードの頭が「WP」が間違いない気がします。

**Comment by niizato** [comment]
![image_2023_9_26](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/81ae8be4-ae9e-4d3e-b2ad-e554fa15ab63)

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！

**Comment by SuzukaKuwabara** [comment]
@niizato 

### ページ名称について

- CREATOR’S SELECT
- Magical Adventure
- ABOUT CREATOR

についてですが、
ハンバーガーメニューの中では

- クリエイターズセレクト
- マジカルアドベンチャー
- クリエイター紹介
 
と、日本語表記にしておいて良いですか？

**Comment by niizato** [comment]
@SuzukaKuwabara 

すみません以前の質問見逃していました！
日本語表記について問題ありません。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！ではそのようにさせていただきます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
### ボトムナビゲーションの仕様について
スマホで見た時、最初はずっと下部に固定されていて、スクロールしていくとフッターの上で止まるような仕様にしてみましたが、こちらいかがでしょうか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/30ab5b14-5c77-4121-9439-c2ab12ac4c95" width="300px">

### シェアボタンについて
特集記事のフッター上に「記事をシェアして感想をお聞かせください」という言葉とSNSのマークが出ると思いますが、そこについてです。
①こちら、プラグインを利用して設置しておりまして、アイコンのデザインが指定できなかったので、元々のデザインと変わっています（facebookのマークが丸になりました。他は同じはずです）

②threadsはまだ公式で対応ができないようで、設置できませんでした。
公式の対応が終わってからの実装とさせてください。


### よく読まれている記事について
こちらは期間を細かく指定できます。
・全期間のうち、よく読まれているもの
・直近１ヶ月のうち、よく読まれているもの
・直近１週間のうち、よく読まれているもの
などから期間を指定できるということです。
どの期間で集計するようにしましょうか？
※後から変更も可能です。
<img width="300" alt="スクリーンショット 2023-10-04 9 52 13" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/f4ae8c17-af30-49a1-849b-05291cfc4fcd">

**Comment by niizato** [comment]
> @niizato
> 
> ### ボトムナビゲーションの仕様について
> スマホで見た時、最初はずっと下部に固定されていて、スクロールしていくとフッターの上で止まるような仕様にしてみましたが、こちらいかがでしょうか？ <img alt="" width="300px" src="https://user-images.githubusercontent.com/109566570/272432402-30ab5b14-5c77-4121-9439-c2ab12ac4c95.png">

こちらのデザインで大丈夫です！

> 
> ### シェアボタンについて
> 特集記事のフッター上に「記事をシェアして感想をお聞かせください」という言葉とSNSのマークが出ると思いますが、そこについてです。 ①こちら、プラグインを利用して設置しておりまして、アイコンのデザインが指定できなかったので、元々のデザインと変わっています（facebookのマークが丸になりました。他は同じはずです）
> 
> ②threadsはまだ公式で対応ができないようで、設置できませんでした。 公式の対応が終わってからの実装とさせてください。
> 

２点の件承知しました。

> ### よく読まれている記事について
> こちらは期間を細かく指定できます。 ・全期間のうち、よく読まれているもの ・直近１ヶ月のうち、よく読まれているもの ・直近１週間のうち、よく読まれているもの などから期間を指定できるということです。 どの期間で集計するようにしましょうか？ ※後から変更も可能です。 <img alt="スクリーンショット 2023-10-04 9 52 13" width="300" src="https://user-images.githubusercontent.com/109566570/272432620-f4ae8c17-af30-49a1-849b-05291cfc4fcd.png">

直近のものはおすすめなどで露出しそうなので、全期間でよく読まれている記事でお願いします

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！！ではご回答の通りで進めますね＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 

### 表記の統一について
「関連特集」「関連する特集記事」が今混在していますが、どちらかに統一をしても良いでしょうか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/df5b57d7-24e4-4fb1-a474-e5b314f97442" width="400px">

### 記事一覧のタグについて
記事一覧に表示するタグの数の制限をしますか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/5e539715-41d3-47be-a423-fce645659c82" width="400px">

**Comment by niizato** [comment]
> @niizato
> 
> ### 表記の統一について
> 「関連特集」「関連する特集記事」が今混在していますが、どちらかに統一をしても良いでしょうか？ <img alt="" width="400px" src="https://user-images.githubusercontent.com/109566570/273084835-df5b57d7-24e4-4fb1-a474-e5b314f97442.png">

関連する特集記事に統一していただいて大丈夫です！よろしくお願いします。

> 
> ### 記事一覧のタグについて
> 記事一覧に表示するタグの数の制限をしますか？ <img alt="" width="400px" src="https://user-images.githubusercontent.com/109566570/273084876-5e539715-41d3-47be-a423-fce645659c82.png">

そうですね。２行に制限した方が良さそうです。

**Comment by SuzukaKuwabara** [comment]
@niizato 
2「行」という制限が多分難しそうな気がします。。確認しますね。

もし２行が難しい場合は「タグ◯個」という感じで個数を決めないといけないので、
３個か４個とかにしておきましょうか。スマホでの見栄え優先ということで。

もちろん、可能であれば２行にしますね！

<img width="400" alt="スクリーンショット 2023-10-06 16 59 48" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/f838b41d-b1e8-45c0-837b-49210332220d">

**Comment by niizato** [comment]
@SuzukaKuwabara 

2行にそこまでこだわりはないので、タグ4個でお願いします！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！タグ４個で対応いたします＾＾
