### ISSUE TITLE
デザイン確認｜　食器ジャーニー

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#10]
@niizato 
現在プロトタイプ準備中ですが、ちょっと確認させてください。

黄色で「NEW」や「PICKUP」と書かれた部分があると思うのですが、こちらについてです。

### ①フォントの種類について
![フォントの確認](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/44e022ea-bcbd-443f-8afb-2a8b9ffc05a9)
英語のところ、デザインデータではInterstateだったのですが、他のページと併せて「見出しゴMB31」にしても良いでしょうか？

### ②右側のサブテキストについて
![サブテキストの確認](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/67dbfc09-ddcf-4dfd-8df4-984cc4014352)
こちら、長い文章になった場合、iphoneSEなど、320pxしかないスマホだと２行になってしまいます。
注意して長くならないようにしていただければ良いかなとは思いますが、
割と長めのテキストを入れるケースもあるのではないかと思って・・

なので

- 注意して入力するのでそのデザインのままで良い
- サブテキストは無しにしてPICKUPだけのデザインにする

どちらが良いかご検討いただけないでしょうか？

よろしくお願いいたします！

**Comment by niizato** [comment]
①フォントの種類について
フォントの確認
英語のところ、デザインデータではInterstateだったのですが、他のページと併せて「見出しゴMB31」にしても良いでしょうか？

＞　「見出しゴMB31」で大丈夫です！

②右側のサブテキストについて
サブテキストの確認
こちら、長い文章になった場合、iphoneSEなど、320pxしかないスマホだと２行になってしまいます。
注意して長くならないようにしていただければ良いかなとは思いますが、
割と長めのテキストを入れるケースもあるのではないかと思って・・

なので

注意して入力するのでそのデザインのままで良い
サブテキストは無しにしてPICKUPだけのデザインにする
どちらが良いかご検討いただけないでしょうか？

＞　２行になっても問題ないのでそのままのデザインでお願いします！

**Comment by SuzukaKuwabara** [comment]
@niizato 
お返事ありがとうございます！
ではその仕様で進めます＾＾

**Comment by SuzukaKuwabara** [comment]
こちら、issueがダブってしまったのでとじますm(_ _)m
