### ISSUE TITLE
トップページ｜　

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#11]

**Comment by niizato** [comment]
イラレデータ


トップページ
https://drive.google.com/file/d/1xR4IUEeaM7Dh4lCD-yrCvYTYXnzgHdCe/view?usp=drive_link

**Comment by niizato** [comment]
<img width="171" alt="スクリーンショット 2023-09-07 14 50 44" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/a02e6701-6503-4562-9935-a9c9fa8c3d2e">

**Comment by niizato** [comment]
@SuzukaKuwabara 

トップページのデータを３箇所修正したので、修正データのリンクを送ります！
1.　インスタグラムの矢印ボタンを他と揃えました。
2.　フッターにSNSのアイコン入れたので「FOLLOW US」を削除しました
3.　文章を変更しています。

**Comment by niizato** [comment]
@SuzukaKuwabara 

フッターのデザインも完了したので確認お願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。
こちらは特集ページのWordpress落ち着いてからの作業となりますので、しばらくお待ちください。

**Comment by SuzukaKuwabara** [comment]
@niizato 
すみませんこちらも閲覧権限がなかったので、
誰でも見れるようにしていただくか、kuwabara@web-knots.comに権限を与えてください＞＜

**Comment by niizato** [comment]
権限変更しました！

**Comment by niizato** [comment]
@SuzukaKuwabara 
ヘッダーの修正をします。

**Comment by niizato** [comment]
<img width="460" alt="スクリーンショット 2023-09-11 15 34 53" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/dd4176d9-5580-4e4c-9cfe-cee9603708b0">

@SuzukaKuwabara 

・ストアトップページのヘッダーにアイコンを追加修正しています。
・ボトムナビゲーションに「ALL ITEM」が追加されたのでトップページMV下あたりに配置していた「すべての商品」を削除しています。
https://drive.google.com/file/d/1m_Z0RHRAeEA4zWiB1yZnN5vhuebx8WoO/view?usp=sharing
