### ISSUE TITLE
トップページ｜　ハンバーガーメニュー

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#13]

**Comment by niizato** [comment]
@SuzukaKuwabara 

ECのトップページ　ハンバーガーメニューのデザインになります。
内容は暫定なので骨組みのデザインです。

https://drive.google.com/file/d/15fTiZYDe0kJdFzUO6YuuUg8ysYz0zK2l/view?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！こちらで進めます＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 

### ヘッダーのメニューについて
↓赤で囲んでいる部分のアイコンは、
ハンバーガーメニューを開いた時だけ表示ということだったでしょうか？
（技術的には可能です）
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/6ecf4a14-a1ee-448d-8fb9-7e345ab70d99" width="400px">

**Comment by niizato** [comment]
@SuzukaKuwabara 

ヘッダーの３つのアイコンは常に表示です。
ボトムナビゲーションにお気に入りやマイページの表示が出来ないと分かる前にお渡ししていたデザインだったので、修正前のヘッダーだと思います。

**Comment by SuzukaKuwabara** [comment]
@niizato
承知しました！ありがとうございます＾＾

**Comment by niizato** [comment]
@SuzukaKuwabara 

ハンバーガーメニューの中の項目になります。
一番上にあった「新商品」は削除しています。

https://docs.google.com/spreadsheets/d/1l68HE6Rh7S23vWuFS4rsbmL25u7_OdTwYJ662uYyfPw/edit?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
承知しました！！ありがとうございます！
