### ISSUE TITLE
デザイン確認｜　404エラーページ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#14]
@niizato 

404エラーページのデザインをお願いしても良いでしょうか？

404エラーページとは、存在しないURLにアクセスしたときに表示されるページです。
例：https://www.hasamiyaki.jp/aaaa

今後、何らかの理由で公開していた記事を削除したりすることもあるかもしれません。
そういったときにどこかのリンクから飛んできて、「存在しないページ」が表示されることがあります。

そのようなときに表示するページのことです。

404エラーページのデザインは、この辺りを参考にされてください＾＾
参考：　https://note.com/archetyp/n/nc1e6c2180203

・親切設計にして、いろんなページへのリンクを貼ったデザイン
・ユーモアを持たせたデザイン
・特にこだわりなければ、マルヒロさんのコーポレートサイトのように、文字のみでシンプルなデザイン

上記のどれかで良いと思います。

急ぎませんので、
こちらマルヒロさんの方で作成お願いしても良いでしょうか？
期限は来週末くらいで大丈夫です。

**Comment by niizato** [comment]
@SuzukaKuwabara 

404のページのデザインができました。
https://drive.google.com/drive/folders/1fPB5buZxAnu2eozu7_yQHehsvSONJ4Jp?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！

**Comment by SuzukaKuwabara** [comment]
@niizato 
先日打ち合わせ時に「404エラーページの画像を、GIF画像にして動かしてみたらかわいいのではないか」というお話をさせていただきましたが、その後いかがでしょうか？

来週末くらいまでにデザインご用意難しそうであれば、一旦今のデザイン（動かないもの）で構築をしてしまおうかなと思いますが、どうでしょうか？＾＾

**Comment by niizato** [comment]
@SuzukaKuwabara 

ちょっとデザイン間に合いそうにないので今のデザインで進行お願いします！

**Comment by SuzukaKuwabara** [comment]
@niizato 
承知いたしました！
