### ISSUE TITLE
全体的な仕様に関わる確認事項

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#15]
全体的な仕様などに関わる確認事項について別途issueを作らせていただきました。

@niizato 

### サブドメインについて
今回、
ec-test.hasamiyaki.jp のサブドメインを作り、
そのドメインを使ってWordPressを構築し
それをmakeshopの「WordPress連携」機能を使って
store.hasamiyaki.jp/blog　に表示させる。

という方法を取っていたのですが、、

Wordpressの管理画面のURLは　`ec-test.hasamiyaki.jp/wp-admin`となりますので、
運用を始めても、ずっと『test』が入ってしまうのが気になるなと。。。
なのでこのドメインを変更したいなと考えています。

最初の段階でそこまで考慮できておらず、大変すみません＞＜

もしマルヒロさんが問題なければ
サブドメインを取り直し、改めてWorpPress連携をしても良いでしょうか？
なお、makeshopさんに確認したところ追加費用などはいらないそうで、無料で対応いただけるそうです。

また、サブドメインの準備もこちらで行います（さくらインターネットの、ゾーン編集というちょっと難しい画面を触ってサブドメインを作る必要があるため）ので、特にマルヒロさんにやっていただく作業も費用もありません。
新たにサブドメイン作るのであれば`ec-edit.hasamiyaki.jp` などがいいかなと思ってます。

いかがでしょうか？

もしよくわからなければまた聞いてください。

**Comment by niizato** [comment]
@SuzukaKuwabara 
サブドメインの件よろしくお願いします。ドメイン名も問題ありません。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。
ではこちらで進めさせていただきます！

**Comment by niizato** [comment]
@SuzukaKuwabara よろしくお願いします！
