### ISSUE TITLE
デザイン確認｜　食器ジャーニー入口&サラフチ入口

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#17]
@niizato 

プロトタイプ確認お願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/be7cc156-617c-45d8-b704-3f6dcbf5f7a8/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/cff1fcb7-e719-4acb-917f-4464d2e01783/

※フッターデザインはまだ適用していませんのでスルーしてください

※こちらも特集ページと同じパーツを使うので、多少デザインデータの余白感から見直しをしています。ですが、どうしても気になる部分は教えてください。

※PC版のアイキャッチ画像（⬇︎）についてですが、固定ページは特集ページとは違って「トリミングされると意味が通じない」ケースも多いと思いましたので、トリミングをしない仕様で考えています。（横幅が900px / 高さは自動調整）
![アイキャッチ画像](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/66ac6943-60d3-4f1e-8cff-43432bc62005)

**Comment by niizato** [comment]
@SuzukaKuwabara 問題ありません！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。開発に進みます！

**Comment by SuzukaKuwabara** [comment]
@niizato 
## 食器ジャーニー入口 (再度)＆サラフチ確認お願いいたします

食器ジャーニー入口の方は、一度ご確認いただいたのですが
サラフチに進んだ際、パーツごとの仕様を統一させる関係で
食器ジャーニー入口の方も余白をちょっと見直したので、再度ご確認お願いいたします。

ほぼ見た目変わらないので、大丈夫かとは思いますが、念の為全てさらっとみていただいて
違和感なければOKのお返事いただければと思いますm(_ _)m

よろしくお願いします。

### 食器ジャーニー入口
■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/be7cc156-617c-45d8-b704-3f6dcbf5f7a8/
■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/cff1fcb7-e719-4acb-917f-4464d2e01783/

### サラフチ入口
■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/6a7a35bf-c52f-4a34-9f40-97d936bb1c62/
■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/c2de89c1-af99-488b-9b3f-653df798a522/

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。ではこれで進めます。
