### ISSUE TITLE
デザイン確認｜　マジカルアドベンチャー

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#18]
@niizato 

プロトタイプ確認お願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/0a7cc7fe-83ea-432e-9806-9198b04e25fb/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/00baffb3-354a-4e94-b72e-bd79b3034b88/

- ※こちらも特集ページと同じパーツを使うので、多少デザインデータの余白感から見直しをしています。ですが、どうしても気になる部分は教えてください。
- 固定ページのアイキャッチ画像（一番上の画像）は、トリミングせず、必ず全体が表示される形式で考えています。
つまり、幅は横幅いっぱい、高さは自動で調整するような感じです。
アイキャッチ画像の中に文字が入るケースも多いだろうと思いましたので、切れないようにという配慮からの仕様です。

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません！
