### ISSUE TITLE
デザイン確認｜　クリエイターズセレクト入口

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#19]
@niizato 

プロトタイプ確認お願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/24b1e6dc-bf1e-4a5b-8a02-372ab022b9c1/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/60faa64b-e55e-411f-8bc4-1fa6c94dd9ea/

**Comment by niizato** [comment]
@SuzukaKuwabara 

ボタンは「ホバーデザイン」のデータが正になります。
「SELECT ITEM」のボタンの色について変更しているのでホバーデザインのデータを確認お願いします！

**Comment by niizato** [comment]
<img width="345" alt="スクリーンショット 2023-09-15 10 06 49" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/2a85bdb6-8847-4001-a4b2-2128b49da1e6">

**Comment by SuzukaKuwabara** [comment]
@niizato 
すみません、色がおかしかったですね；
こちら、、修正して開発に進みます。

![スクリーンショット 2023-09-15 10 31 30](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/6ccfb42a-7ccf-48b1-af36-e0d3fe17ae4f)
