### ISSUE TITLE
デザイン確認｜　アバウトクリエイター入口

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#20]
@niizato 

アバウトクリエイターのプロトタイプチェックお願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/9af12634-6d7c-48a5-b89a-27e08cdca645

■ PC　
https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/0cd190e3-8981-448e-b9fd-c37675afb3ce

**Comment by niizato** [comment]
<img width="804" alt="スクリーンショット 2023-09-15 10 12 31" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/b3dd7332-7fde-4dc9-8b63-8d16c87f5071">

**Comment by niizato** [comment]
@SuzukaKuwabara 

ボタンのデザインを変更しているので、ホバーデザインのデータをご確認ください。

**Comment by SuzukaKuwabara** [comment]
@niizato 
すみません、こちらもホバーデザインの方に修正できておりませんでした。

こちらを修正して、開発に進みます！
