### ISSUE TITLE
デザイン確認｜　アーティスト入口ページ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#21]
@niizato 

アーティスト入口ページのプロトタイプチェックお願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/4f0f6ce0-da0e-4b57-9935-c0be75d24be0/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/c09e7127-3f96-4cb0-afee-134b4b743c1b/

**Comment by niizato** [comment]
@SuzukaKuwabara 

確認しました。PCの方に修正のコメントを入れています。

**Comment by SuzukaKuwabara** [comment]
@niizato 
スライダー部分については、アーティスト詳細ページと同じ点について確認したいです。
アーティスト詳細ページのissueでご回答ください。

他は問題ないのでご指示通り修正いたします！

**Comment by SuzukaKuwabara** [comment]
@niizato
アーティスト入口ページ

いただいていた修正、全て完了しました。
こちらで構築進めております！

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/4f0f6ce0-da0e-4b57-9935-c0be75d24be0/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/c09e7127-3f96-4cb0-afee-134b4b743c1b/

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません！
