### ISSUE TITLE
デザイン確認｜　アーティスト一覧

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#22]
@niizato 

アーティスト一覧ページのプロトタイプチェックお願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/fc36537e-8b7a-4fc8-a03d-9693d6a0204c/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/14e3f3d9-5a44-4138-8013-43853241cb9b/

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません
