### ISSUE TITLE
デザイン確認｜　アーティスト詳細ページ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#23]
@niizato

アーティスト詳細ページのプロトタイプチェックお願いいたします。

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/39a66ba5-d029-4ac0-9d90-f1f52f70869e/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/03f932d6-5788-4fe9-8cb4-1a3e0a4616c5/

**Comment by niizato** [comment]
@SuzukaKuwabara 

XDに修正書き込んでいます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
「スライダーを中央にしたい」の部分についてです。（アーティスト入口ページも同様です）

中央に持ってくることはできますが、
・その場合はSPもPCもスライダーを削除させてください
・PCでは、対象の商品が５〜６個ないと崩れやすくなるかなぁとおもうのですが、対象の商品数についてはどのアーティストさんも問題なさそうでしょうか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/11b7db1c-0e9f-48b7-a127-a7dd09eaea0e" width="500">


上記以外の修正は対応できますので、ご指示通り修正します！

**Comment by niizato** [comment]
@SuzukaKuwabara 


・その場合はSPもPCもスライダーを削除させてください
＞PCと同様で大丈夫です。

・PCでは、対象の商品が５〜６個ないと崩れやすくなるかなぁとおもうのですが、対象の商品数についてはどのアーティストさんも問題なさそうでしょうか？
＞対象の商品が２つの人もいます。他のデザインで解決案などありますか？
スライダー機能なしで、並べるだけでも大丈夫ですが多い人で20商品ぐらいある人もいます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ちょっと考えてみますね。お待ちください。

**Comment by SuzukaKuwabara** [comment]
@niizato 

考えてみました。
こんな感じで、
・PCでは最大４件のみ表示＆スライダーにしないで中央揃え
・SPではスライダーで登録した商品は全て表示
でどうでしょう？
![グループ 4088](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/c7c0be83-76e8-403e-ba16-9f8775babbc9)

**Comment by niizato** [comment]
@SuzukaKuwabara 

それでお願いします！

**Comment by SuzukaKuwabara** [comment]
@niizato 
承知しました！
では修正全部終わりましたらまた連絡いたしますね。

**Comment by SuzukaKuwabara** [comment]
@niizato 
アーティスト詳細ページ

いただいていた修正、全て完了しました。
こちらで構築進めております！

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/39a66ba5-d029-4ac0-9d90-f1f52f70869e/

■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/03f932d6-5788-4fe9-8cb4-1a3e0a4616c5/

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません！
