### ISSUE TITLE
ユーザーの作成について

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#24]
新しいWordpressにユーザーを作っておきたいと思います。

登録したいユーザー情報をご提示いただいても良いでしょうか？
いただきたい情報は
・ユーザー名（英数字）
・表示名（日本語のおなまえなど）
・メールアドレス
です。

①管理者権限　最低１名
②編集者権限　日常的にサイトの更新をされる方　何名でもOK

以上、ご用意をお願いいたします。

**Comment by niizato** [comment]
@SuzukaKuwabara 

管理者
ユーザー名　MARUHIRO
表示名 マルヒロ
メール　design@hasamiyaki.Jo

編集者1
ユーザー名 Niizato
表示名 新里
メール niizato@hasamiyaki.jp

編集者2
ユーザー名 Etou
表示名　衞藤
メール etou@hasamiyaki.jp 

編集者3
ユーザー名 Mori
表示名　森
メール mori@hasamiyaki.jp

編集者4
ユーザー名 Murata
表示名　村田
メール murata@hasamiyaki.jp

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。
下記のパスワードでユーザーを作りましたので、入っていただけます。
よろしくお願いいたします。


管理者
ユーザー名　MARUHIRO
表示名 マルヒロ
メール　[design@hasamiyaki.Jo](mailto:design@hasamiyaki.Jo)
PASS　WeFuiuLLJo)H6icAq7v7&k#f

編集者1
ユーザー名 Niizato
表示名 新里
メール [niizato@hasamiyaki.jp](mailto:niizato@hasamiyaki.jp)
PASS　VKetGhVfoMxcgcIbfO@UqvWZ

編集者2
ユーザー名 Etou
表示名　衞藤
メール [etou@hasamiyaki.jp](mailto:etou@hasamiyaki.jp)
PASS　v3OwLw9tGy%jnQcE8VL(WR^a

編集者3
ユーザー名 Mori
表示名　森
メール [mori@hasamiyaki.jp](mailto:mori@hasamiyaki.jp)
PASS　uhmzXBZXRJRMsj*xW*!#2Ib^

編集者4
ユーザー名 Murata
表示名　村田
メール [murata@hasamiyaki.jp](mailto:murata@hasamiyaki.jp)
PASS　xkuppb*G*CfP8F7qg6pBMEwA
