### ISSUE TITLE
不足画像

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#25]
* OGP画像（1200x630）
    * デフォルト画像（ダミー画像）1200 x 480px

**Comment by niizato** [comment]
![OGP画像](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/3720ac3f-f968-4b96-8ef1-ec4cac674ee1)

**Comment by niizato** [comment]
![デフォルト画像](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/c92f39f1-a478-4b39-a3df-fb34f1b211ea)

**Comment by niizato** [comment]
@SuzukaKuwabara 

OGP画像とデフォルト画像になります。ご確認お願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！

**Comment by SuzukaKuwabara** [comment]
@niizato 
OGP画像ですが、png形式でいただくことは可能でしょうか？すみません；

**Comment by SuzukaKuwabara** [comment]
@niizato 
度々すみません。

ダミー画像もpngでお願いできますか？（こちらはjpgでもpngでもいいのですが、簡単な画像なので、pngの方が軽くなりそうなので）

**Comment by niizato** [comment]
![OGP画像](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/f48eb76e-e797-434d-bf8a-5f59a57b93e8)

**Comment by niizato** [comment]
![デフォルト画像](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/40ef081a-dc72-43e2-a5f8-3fee68f65cab)

**Comment by niizato** [comment]
@SuzukaKuwabara よろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！！
