### ISSUE TITLE
メニューのリンク先について

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#26]
メニューのリンク先について
こちらに書き込みをお願いします。
（会議で説明します）

https://docs.google.com/spreadsheets/d/1UUgMnTip6s5-KLj9tRqAEw5iHBX1pwNQN2pMyH3Z2nw/edit#gid=990329330

**Comment by SuzukaKuwabara** [comment]
@niizato 
リンク先について確認です。

・配送について
・お届けについて
・配送料について

この３つは別々のページに作成しますか？
それとも１ページに作成して、該当の箇所にページ内リンクさせますか？
![スクリーンショット 2023-10-12 19 00 13](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/b68509df-0135-4633-ac54-d6b5a7e2b6ec)

**Comment by niizato** [comment]
@SuzukaKuwabara 

以下、全て「ご利用ガイド」内に作成してページ内リンクにします。
利用案内をメイクショップに作ると記載しておりましたが、新規作成にします。

- 配送について
- 利用案内（ご利用ガイドに変更）
- お届けについて（配送についてと同じなので名称を配送についてに合わせる）
- 配送料について
- お支払いについて
- キャンセル・返品・交換

**Comment by niizato** [comment]
@ETOmaruhiro 

上記よろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 

ありがとうございます。
固定ページ、作成完了しておりますのでいつでも執筆に取り掛かっていただいて大丈夫です。

リンクもスプレッドシートに記載しました
https://docs.google.com/spreadsheets/d/1UUgMnTip6s5-KLj9tRqAEw5iHBX1pwNQN2pMyH3Z2nw/edit#gid=990329330

![FireShot Capture 121 - 固定ページ ‹ マルヒロオンラインショップ — WordPress - ec-edit hasamiyaki jp](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/cb098c26-8c65-4c3a-b95f-15dd20ba0f31)
