### ISSUE TITLE
不足画像の提出・リンク先指定のお願い

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#28]
@niizato
不足している画像についてまとめてお知らせします。

また、併せてリンク先も指示をいただくことは可能でしょうか？
こちらで調べれば分かることではあるのですが、スムーズに作業を進めるためにリンク先のリストアップにご協力いただけないでしょうか。

### 期限について
- TOPページに関するものは10/25を目処に
- カテゴリーページに関するものは11/7を目処に
 
と言う期限を目処にご用意ください。

### ご用意いただきたい画像・リンク先
- [x] EC-TOPページ：丸い５個のところ
- [x] EC-TOPページ：小さいCATEGORY
- [x] EC-TOPページ：BRAND/SERIES
- [x] EC-TOPページ：ギフト・プレゼント
- [x] カテゴリーページ：シリーズ
- [x] カテゴリーページ：アイテム / 皿・プレート
- [x] カテゴリーページ：アイテム / 腕・ボウル
- [x] カテゴリーページ：カテゴリー

### 画像について注意点
- 正方形にしたいものは正方形にトリミングしていただけると嬉しいです。
丸い画像は正方形でご提出ください。CSSでトリミングします。（その方がなにかと使い勝手がいいと思うので）
- 画像の横幅は、PCのレイアウトが決まってないのでなんとも言えない部分ですが、ひとまず800〜1200px程度に書き出してご用意ください。

### リンク先について
こちらに書き込みお願いいたします。

https://docs.google.com/spreadsheets/d/1UUgMnTip6s5-KLj9tRqAEw5iHBX1pwNQN2pMyH3Z2nw/edit#gid=990329330

黄色い部分です。画像を右側に貼り付けています。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/a9afbc1b-7154-4a53-98e2-0ba66e180b66" width="400">

**Comment by niizato** [comment]
@SuzukaKuwabara 
丸い画像ですが、すでに丸に切り抜いて準備していたのですが、正方形で作り直した方が良いですよね？

**Comment by SuzukaKuwabara** [comment]
@niizato 
そう言うことなら大丈夫です＾＾
もしも正方形がないと困る状況になったらまた相談します。多分問題ないです。

**Comment by niizato** [comment]
@SuzukaKuwabara 

E Cトップページの不足画像になります。
https://drive.google.com/drive/folders/1xW3kOIF9bU01nCz4ADz8-6Ytqymd-wD8?usp=sharing

**Comment by niizato** [comment]
@SuzukaKuwabara 

カテゴリーページの「シリーズ」の画像はissue＃12にてお渡し済みです。

**Comment by SuzukaKuwabara** [comment]
@niizato 
はい！そちらの画像はご提出いただかないで大丈夫です！
リンク先のみスプレッドシートに入力のご協力お願いいたします。

**Comment by niizato** [comment]
@SuzukaKuwabara 
カテゴリーページの不足画像になります。

<img width="1313" alt="スクリーンショット 2023-10-16 13 08 54" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/8c113869-0436-4d39-bf11-44f2c770402c">


https://drive.google.com/drive/folders/15vbd39n5vNJcaiFQ6HUnZ9GmXv1IgpeZ?usp=sharing

**Comment by Murata-Maruhiro** [comment]
URL一通り貼り終わりました。
「新生活」だけがどうしても見つけることができず、URLは空欄にしております。
ご確認の程よろしくお願いいたします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
画像ありがとうございます！

「新生活」のURLは分かり次第で大丈夫です！

**Comment by niizato** [comment]
@SuzukaKuwabara 

村田さんにちゃんと説明ができていなかったのですが、新規作成の部分はURL不要です。修正しておきます。
