### ISSUE TITLE
構築完了確認：固定ページ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#29]
@niizato 

元々デザインのあった固定ページ等が全て構築済みですので、見た目のご確認お願いいたします。（PC,SPでご確認ください）
内容は全てダミーです。見た目のみご確認ください。

なお、固定ページは記事の編集を始めていただいて構いません。

- [x] 全てのタグページ　https://store.hasamiyaki.jp/blog/tags/
- [x] アバウトクリエイター　https://store.hasamiyaki.jp/blog/about-creator/
- [x] アーティスト紹介　https://store.hasamiyaki.jp/blog/artists/
- [x] CREATOR’S SELECT　https://store.hasamiyaki.jp/blog/creators-select/
- [x] サラフチ　https://store.hasamiyaki.jp/blog/sarafuchi/
- [x] Magical Adventure　https://store.hasamiyaki.jp/blog/magical-adventure/
- [x] 僕らの食器ジャーニー　https://store.hasamiyaki.jp/blog/tableware-journey/
- [x] 検索ボタンを押した時のページ（右上検索ボタンを押して確認ください）
- [x] 全てのアーティスト　https://store.hasamiyaki.jp/blog/artist/
- [x] ニュース一覧　https://store.hasamiyaki.jp/blog/news/
- [x] ニュース詳細　https://store.hasamiyaki.jp/blog/news/kakunin/

### 特筆事項
- 今気づいたのですが、検索ボタンを押した時に、ページ下部に「人気のタグ」が抜けていたので修正します。すみません。
- 全てのアーティストページについて：こちらのページは固定ページではなく性質的に「アーカイブページ」と言う分類になるのですが、この関係で、デザインデータにはあった「関連コンテンツ」と「特集ピックアップ新着記事」が表示できません。。ご了承をいただけないでしょうか。
<img width="400" alt="スクリーンショット 2023-10-13 5 53 43" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/8b520197-6255-47a7-aefe-a94b4037be53">

**Comment by niizato** [comment]
<img width="1164" alt="スクリーンショット 2023-10-13 9 55 44" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/1151f385-ef59-40d7-942a-17ed0e916be5">

@SuzukaKuwabara

そこまで重要じゃないかもしれませんが、ダミー画像のサイズが違います。

**Comment by niizato** [comment]
<img width="1548" alt="スクリーンショット 2023-10-13 10 02 11" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/7fd8dfc3-226e-42e6-ad76-723b3d4ed2a7">

@SuzukaKuwabara 
ニュース詳細のトップイメージの位置がずれています。

**Comment by niizato** [comment]
<img width="854" alt="スクリーンショット 2023-10-13 10 03 12" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/568511f2-fcf8-447a-9b14-ea4fb6ea70d8">
<img width="1488" alt="スクリーンショット 2023-10-13 9 59 04" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/e02615b6-3e4e-4c22-b9c9-013017c58cf7">
@SuzukaKuwabara 

404のページについてPCでの見た目もSPと揃えていただきたいです。

**Comment by niizato** [comment]
@SuzukaKuwabara 

▼こちら承知しました

特筆事項
今気づいたのですが、検索ボタンを押した時に、ページ下部に「人気のタグ」が抜けていたので修正します。すみません。
全てのアーティストページについて：こちらのページは固定ページではなく性質的に「アーカイブページ」と言う分類になるのですが、この関係で、デザインデータにはあった「関連コンテンツ」と「特集ピックアップ新着記事」が表示できません。。ご了承をいただけないでしょうか。

**Comment by niizato** [comment]
@SuzukaKuwabara 

SPを使って確認ができませんでした。パスワードを求められたのですが

VKetGhVfoMxcgcIbfO@UqvWZ
maruhiro23

どちらもパスワードが正しくないと言われてしまいました。

**Comment by SuzukaKuwabara** [comment]
@niizato 

ご確認ありがとうございます！

### 404ページとアーティスト一覧について
こちらの環境では同じように表示されないんですよね・・・
一度スーパーリロード（WindowsではCtrl + F5キー 。Macではshift + cmd + Rキー）をしてみて、それでも改善されない場合、
・みているブラウザ（Chromeやsafariなどの種類）
・パソコンの種類（macかWindowsか。windowsの場合[Window11]などのバージョンまで）
を教えてください。

### NEWSのアイキャッチ画像のずれ
→こちらは修正いたします。ご指摘ありがとうございます！


### SPの時の確認について
maruhiro23でいけるはずではありますが、
パスワード保護をしていることで確認作業がいちいち煩雑になりますので、
一時的に保護を解除しようと思っています。

確認作業ができそうなタイミングで、チャットワークで声をかけていただけないでしょうか。
保護を解除します。
その後、確認完了したらまたもとにもどしたいとおもいます。

**Comment by niizato** [comment]
> @niizato
> 
> ご確認ありがとうございます！
> 
> ### 404ページとアーティスト一覧について
> こちらの環境では同じように表示されないんですよね・・・ 一度スーパーリロード（WindowsではCtrl + F5キー 。Macではshift + cmd + Rキー）をしてみて、それでも改善されない場合、 ・みているブラウザ（Chromeやsafariなどの種類） ・パソコンの種類（macかWindowsか。windowsの場合[Window11]などのバージョンまで） を教えてください。

スーパーリロードで問題なく確認できました！

> 
> ### SPの時の確認について
> maruhiro23でいけるはずではありますが、 パスワード保護をしていることで確認作業がいちいち煩雑になりますので、 一時的に保護を解除しようと思っています。
> 
> 確認作業ができそうなタイミングで、チャットワークで声をかけていただけないでしょうか。 保護を解除します。 その後、確認完了したらまたもとにもどしたいとおもいます。

もう一度ログインしてみたらできたのでSPで確認作業に入りますね

**Comment by niizato** [comment]
@SuzukaKuwabara 

SP での確認終了しました。問題ありません！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ご確認ありがとうございます！
ではあとは固定ページの作成、マルヒロさんの方でよろしくお願いいたします。

作りながら困った点がありましたらお知らせください！
