### ISSUE TITLE
デザイン確認｜　NEWS一覧・詳細ページ

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#3]
■ NEWS詳細ページについて

こちら、上のものよりも優先度低いのですが質問です。

文章の中にテーブル（表）があると思うのですが、この表の文字サイズは、添付している特集記事内に使われるテーブルと同じ（11pxにしています。やや小さめ。）にしますか？

↓ちなみにこちらは、本文の文字サイズに合わせてちょっと大きく（14px）してみたverです。この料金表のように、複数行におよぶ表の場合はちょっと見づらいですが、２列くらいの表であればちょうど良いサイズです。
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/5f552dc1-14f8-4521-b13a-dadd80f956fa
どうでしょうか？

↓テーブルを使っている特集記事
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/

※なお、構築の関係で二つの表の文字サイズなどの仕様は同じにしたいです

★今週の木曜日くらいまでにお返事いただけると幸いです。

**Comment by niizato** [comment]
14pxの方が見やすいのでそちらにしたいのですが

↓テーブルを使っている特集記事
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/

こちらの表で文字量が多い場合、どのような見た目でズレていきますか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
サイズや原産地等をテーブルで表記する部分ですが、
14pxで行くのであれば、はみ出してしまい、見づらいので
縦並びにするのが現実的かなと思います。

デモを作りましたので比較してみてください。
https://xd.adobe.com/view/80b8e876-93ed-43c1-aaa5-cfa532f92aeb-d5eb/

※14pxで行く場合、表内の余白をもうちょっと取っても良いかもですね

![スクリーンショット 2023-09-04 12 33 08](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/bad8307a-f9fe-4c4b-a691-1aa969c19eff)

**Comment by SuzukaKuwabara** [comment]
（基本雛形に関わるので急ぎにさせてもらってます）

**Comment by niizato** [comment]
@SuzukaKuwabara 

14pxの縦並びでお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。
ここの余白、文字が大きくなった分1~2pxだけ多めに取っておきます。

<img width="360" alt="スクリーンショット 2023-09-04 14 37 34" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/1a748147-9b65-4465-8fc6-bc3383b7ba59">

ではテーブルについての確認はOKですね。
修正後、またNEWS詳細ページの確認をお願いしますのでお待ちください。

**Comment by SuzukaKuwabara** [comment]
@niizato 
プロトタイプができましたのでご確認お願いいたします。

【特に確認していただきたいところ】
①一覧ページの、コンテンツ部分の余白はほかのページと揃えています。（デザインデータではもうちょっと余白とってあったのですが）良いかどうか。
![スクリーンショット 2023-09-06 12 07 51](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/127149e2-154a-4afe-a967-0b89eeea9a2a)

②テーブル（表）については、基本のスタイルが適用されますので、基本的に訂正なしでお願いします。１列あたりの横幅など気にあるかもしれませんが、これと全く同じにはならないと思います。ここは実際に構築してみて、どういうふうになるかみてもらってから微調整必要なら検討させてください。


**一覧**
■ SP
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/b9c33036-be81-4ccd-9c89-c6293cfa145a/

■ PC
https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/50e714cc-a964-479f-becc-3d02d1f8923b/

**詳細**
■ SP
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/5f552dc1-14f8-4521-b13a-dadd80f956fa/

■ PC
https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/0cd3842b-39df-4aad-82ba-b98bcaefd7bd/

**Comment by niizato** [comment]
問題ありません！よろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。構築に進みます！
