### ISSUE TITLE
カテゴリ再設定

### ISSUE THREAD

**Issue by ETOmaruhiro** [niizato/MARUHIRO-onlineshop-renewal#30]
カテゴリ「その他」の中身を整理し、カテゴリの再設定の必要があるものは再設定をする。

・カテゴリ中身整理：新里
・再設定：村田

**Comment by niizato** [comment]
@Murata-Maruhiro 


**カテゴリを移動したので該当商品は商品登録し直し**
 
・箸置き・カトラリー
・「キーホルダー」　削除したので「本・雑貨」に移動
・木製品・漆器を削除したのでそれぞれのアイテムへ移動。重箱は「季節」へ
 
 
**カテゴリ名称変更　登録商品に相違ある場合は修正**
 
服飾雑貨・布製品　→　ファッション
紙製品・ステッカー　→　本・雑貨
