### ISSUE TITLE
目次

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#32]
<img width="780" alt="スクリーンショット 2023-10-16 13 49 49" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/564a8425-e01a-44e6-a869-74e6177d7e21">

**Comment by niizato** [comment]
@SuzukaKuwabara 

今日気づいて申し訳ないのですが、目次のプラスマークは閉じる時にマイナスマークになりませんか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
できると思いますので、修正しますね＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 

こちら修正いたしました！

<img width="884" alt="スクリーンショット 2023-10-17 11 40 44" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/41c5c8a3-1331-4d20-8fa2-dfd64e7ba596">
