### ISSUE TITLE
表示速度改善について

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#33]
経緯を残しておきたかったので、issueを立てました。

## 現状
重たいページでプロキシエラーが出てページが表示されない。
store.hasamiyaki.jp のドメイン配下の場合にのみプロキシエラーは出現
ただし、ec-edit.hasamiyaki.jp ドメインで表示してもかなり表示までの時間が長く、改善が必要。

**原因**
プロキシエラーは、おそらく読み込みに時間がかかりすぎることでmakeshop側でタイムアウトしてしまい、起こっているようです。
このタイムアウトの時間設定などは、ストアごとに個別に変更することはできませんとのことでmakeさんより回答いただき、makeshop側に解決の糸口を見出すことは不可能と判断。

今回、いろいろなブロックを積み重ねてコンテンツを作っているが、ブロックが増えれば増えるほど重たくなってしまうのは紛れもない事実で、「ページが重たいは場合はブロック数を少なくするしかない」という点についてはマルヒロさんにも今後ご認識いただかないといけません。

ただ、重いブロック・軽いブロックというものはあり、ブロックの数が多くてもテキストや画像ばかりであれば特に問題はなかったりします。しかし、他のデータベースから情報を読み込ませるようなブロックは負荷が高いようです。つまり、便利に使えるようにすればするほど表示速度に影響が出ているということです。

**ちなみに、何が一番重たいブロックなのか**
”同じカテゴリの商品”を実装するための「商品セットスライダー」が最も重たい。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/489e582e-a02e-4977-bd60-779d59fc2f72" width="300">
商品データベースを元に作成した「商品セット」から商品を呼び出してくるという、二重にループが発生しているためデータの呼び出しに時間がかかるようです。

このパーツを使わないだけでも読み込み速度はかなり改善します。
ただ、このパーツはECサイト内の別の商品購入につながる、無くしたくない重要なパーツなので、どうにか利用できる策を見つけたいと思っています。

### ①Wordpressの中でできるスピード改善施策
プラグインを用いたコードの軽量化・webpの導入など、できることは行いました。（これによりカスタムブロックをたくさん使わないページはかなり早くなった）

### ②サーバーの変更
WPを設置するサーバーをエックスサーバー→さくらインターネットに変更してみる。
表示速度はそこまで変わらないが、PHPのバージョンを最新にできるので、10/17に引っ越しを行う。
この時点ではまだmakeshopさんと連携していないので、プロキシエラーは起こらない（が、重いページは重たい）

### ③makeshopさんにWP連携を行なってもらう
サーバーを変えても重たいので、連携をすることでおそらくタイムアウトを起こしてしてプロキシエラーが起こるのではないかと予測しているが、果たしてどうか。10/18実施予定。

✅ここで問題が解決すればそれでOK。ダメなら④へ

### ④表示する商品点数をもっと制限する
表示する商品点数をもっと少なくすることで、少しでも負担を減らすことができないか。
現在、複数の商品セットをタブ切り替えで表示でき、表示する点数も多めなので、この数を制限することで少しでも負荷を減らす。

✅ここで問題が解決すればそれでOK。ダメなら⑤へ

### ⑤商品セットを手入力に変更
商品データベースからの呼び出しをせず、商品セットは自力で作成する。（画像やリンク先・価格を自分で入力して商品セットを作成するということです。。）
この便利機能を諦めることでおそらくかなり改善できるのではと思っておりますが、これは最後の最後の手段にしたいと思います。

**Comment by SuzukaKuwabara** [comment]
@niizato 
経緯の保存のためにissue作成しました。
軽く目を通していただければOKです。

**Comment by niizato** [comment]
@SuzukaKuwabara 

色々とありがとうございます！
④の段階で、下に「一覧を見る」ボタンがあるのでスライダーをなくしても大丈夫です。

**Comment by SuzukaKuwabara** [comment]
@niizato 
本日も野尻さんと検討を重ねまして、
解決策を見出せました！！

>④の段階で、下に「一覧を見る」ボタンがあるのでスライダーをなくしても大丈夫です。

→こちらのスライダーの機能については、諦めなくても大丈夫そうです＾＾


解決策については別途書き込みます。
少しお待ちください。

**Comment by SuzukaKuwabara** [comment]
@niizato 

表示速度が遅い件についてです。

悪さをしているのが、「商品データベースにて、商品画像をmakeshopから持ってくるやり方」ということがわかりました。現在は、makeshopから商品画像を持ってきているので、自分達で一つ一つの画像を登録する必要がないのですが、これを解決するためには一つずつ画像の設定が必要そうです。

ただ、一度設定してしまえば、そのあと商品のCSVを上書きしても、画像は消えないです。

この手法に変えると、劇的に表示スピードは速くなりました。
エラーはもちろん出ませんし、かなりサクサクで快適です。

画像の設定はどうしてもマルヒロさんにやっていただく必要があるのですが、なにせ商品点数が多いので、非常に手間を増やしてしまうのですが、表示スピードは非常に深刻な問題でしたので、【商品画像を１商品につき１枚ずつ、手動で設定していただく】という変更に、ご了承いただけないでしょうか。

**Comment by niizato** [comment]
@SuzukaKuwabara 

承知しました！頑張ります！

@ETOmaruhiro @Murata-Maruhiro @mori-maruhiro 
工数が増えましたがページが重いのは致命傷なのでご協力よろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
@mori-maruhiro 

ありがとうございます。要らぬ手間を増やしてすみません＞＜
設定方法については追ってご説明いたします！

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
@mori-maruhiro 

現在、このように商品画像がダミー画像に変更になって表示されているものが多々ある状態になっています。
崩れたりしていますが一旦気にせず更新を続けていただいて大丈夫です。
後から画像を設定したら直ります。

<img width="1060" alt="スクリーンショット 2023-10-19 16 33 09" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/2e6374fc-5033-460b-a68c-978a159a258e">

**Comment by mori-maruhiro** [comment]
@SuzukaKuwabara 
お疲れ様です。
【商品画像を１商品につき１枚ずつ、手動で設定】について、承知いたしました。
商品セットの画像サイズですが、800×800で良かったでしょうか？

**Comment by SuzukaKuwabara** [comment]
@mori-maruhiro 
はい、800x800で問題ありません！
設定方法について、動画でまとめたのでのちほどチャットワークにお送りいたしますね。
