### ISSUE TITLE
関連特集｜1つめの記事だけ大きく表示のデザイン修正

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#34]
@SuzukaKuwabara 
1枚目の記事の概要がわからないので表示させる

<img width="693" alt="スクリーンショット 2023-11-04 13 35 52" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/b247cd37-e5a4-4f02-b915-c112cfc8ec61">

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！修正します。

**Comment by SuzukaKuwabara** [comment]
@niizato 
こちら対応完了しました！ご確認ください。

**Comment by niizato** [comment]
@SuzukaKuwabara こちら見逃していました！ありがとうございます。
