### ISSUE TITLE
特集ページ / スライダーの仕様について

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/MARUHIRO-onlineshop-renewal#35]
@niizato 

スライダーにキャプションをつけられたら便利そうとのことで、実装自体は可能ですがいくつか確認したいことがあります。

キャプションの文章量に違いがあるとスライダーの次の要素までの間に
スペースが空いたように見えてしまうので、
文字を写真の下につけたい場合は、
文章量に違いが出ないように配慮をする必要があります。

<img width="600" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/f3d18f72-dd30-4abc-b77e-aa3c35b3cfb8">

---

そのため、この配慮が難しそうな場合は、
こちらのように、写真の上にキャプションを載せるレイアウトもアリです。
<img width="600" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/557cb12e-cac9-43a3-a8d5-c052709bdec5">

どうされますか？
①文字量を自分達で調整するので写真の下にキャプションをのせたい
②写真の上にキャプションを載せるレイアウトにする
どちらかかな、と思うのでご検討後お返事いただけますと幸いです。

**Comment by SuzukaKuwabara** [comment]
@niizato 
こちらってどこにお返事が書いてあるでしょうか・・・？見つけられず；

**Comment by niizato** [comment]
@SuzukaKuwabara 

こちらすみません。もしかしたらコメントのボタン押さずに閉じてしまったのかもしれません。

①文字量を自分達で調整するので写真の下にキャプションをのせたい

上記でお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
大変お待たせいたしました。
スライダーにキャプション機能を追加しました。
確認用の記事を作っているので、こちらのプレビューでご確認ください。
https://store.hasamiyaki.jp/blog/?p=17299&preview=1&_ppp=09ff3242ab

正方形の方は問題なく使っていただけるかと思います。


長方形の方は、キャプションを入れることで
・矢印の位置が中央より下にずれてしまう
・スライダーがかなり離れたように見えてしまう
というデメリットがあります。。。

このままで良いということであればそれでも良いのですが、
もし改善するとしたら
「長方形スライダーでキャプションが入った時は、以前ご提案した”写真の上に重ねる仕様”にする」
というやり方も可能です。

どうしましょうか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
長方形スライダーの仕様を変更しました。
（長方形スライダーの時はキャプションを画像の上に重ねる）

こちらのテスト記事で見た目をご確認ください。
https://store.hasamiyaki.jp/blog/?p=17299&preview=1&_ppp=e444ca18a6

**Comment by niizato** [comment]
@SuzukaKuwabara 

ありがとうございます！OKです。
