### ISSUE TITLE
トップページ｜インスタの部分デザインを変更する

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#38]

**Comment by niizato** [comment]
<img width="461" alt="スクリーンショット 2023-12-02 14 58 27" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/63fcc10f-85d9-4276-88e5-7bc786af2ff4">

**Comment by niizato** [comment]
@SuzukaKuwabara 

TOPページインスタ部分のデザインができたので以下よりデータのダウンロードお願いします。
https://drive.google.com/drive/folders/1KP6FlwFmhqa2mDrfVtmJRrnbBtI2r8Sr?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！適用します。

**Comment by SuzukaKuwabara** [comment]
@niizato 
インスタの部分適用完了しましたのでご確認ください。

TOPページ用WP　（PC、SP共にご確認ください）
https://hasamiyaki.jp/store-backend/new-home/

問題なさそうであれば、良いタイミングでmakeshopへの貼り付けをお願いしても良いでしょうか。

**Comment by niizato** [comment]
@SuzukaKuwabara 

ありがとうございます！早速この後貼り付けます。
