### ISSUE TITLE
デザイン確認｜　人気ランキング

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#4]
■ 人気ランキング
SP 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/8d522149-f961-4cb3-b78c-2ae0e3219345
PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/abde9eb3-c50f-4cfa-8810-d10e33cd3871

**Comment by SuzukaKuwabara** [comment]
@niizato 
修正なしですので開発に進みます。
