### ISSUE TITLE
ECトップページ｜PC 全体デザイン

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#41]
<img width="1287" alt="スクリーンショット 2023-12-01 10 29 50" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/59ebd6f5-dfdd-4ecc-94a4-f5708f446ab7">

**Comment by niizato** [comment]
@SuzukaKuwabara 

1　画像サイズを1200x800に変更できますか？
2　スペースを広げてください
3　スペースを広げてください。＜popular titems＞下のグレーのラインはなしで大丈夫です。

**Comment by niizato** [comment]
<img width="1287" alt="スクリーンショット 2023-12-01 10 29 50" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/c67feb70-fff7-4a79-a217-ba41a27afda6">

**Comment by niizato** [comment]
<img width="1265" alt="スクリーンショット 2023-12-01 11 49 23" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/6d0e8eea-2bc2-443e-a4b4-6eae98e1e9fd">

**Comment by niizato** [comment]
@SuzukaKuwabara 

ヘッダーの＜よみもの＞が端すぎるので、MVのテキスト位置まで右寄せお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 

・メインビジュアルの縦横比を1200x800（2:3）に修正しました。
　SPでは正方形で表示していますがよろしいでしょうか？

・POPULAR ITEMのところはスライドバーを削除しました。
　また、上下の余白を少し大きくしました（PCのみ）。

・ヘッダーの「よみもの」のところ
すみません、ここ、うっかりしていたのですが「広」のマークを入れるんでした（TOPページ用WPではそのようになっていたかと思います）
入れてみたので、この状態で改めてチェックお願いいたします！

<img width="400" alt="スクリーンショット 2023-12-01 12 52 03" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/9ccf5bcb-965d-4b2b-98c4-db6b28624d51">

**Comment by niizato** [comment]
> ・メインビジュアルの縦横比を1200x800（2:3）に修正しました。 　SPでは正方形で表示していますがよろしいでしょうか？
ありがとうございます！SPで正方形でOKです。


> ・POPULAR ITEMのところはスライドバーを削除しました。 　また、上下の余白を少し大きくしました（PCのみ）。
OKです！


> ・ヘッダーの「よみもの」のところ すみません、ここ、うっかりしていたのですが「広」のマークを入れるんでした（TOPページ用WPではそのようになっていたかと思います） 入れてみたので、この状態で改めてチェックお願いいたします！
こちらも気づかずすみません。少し右に寄せていただけますか？画像に赤線で十字を入れたので中央にマルヒロがくる感じで

**Comment by niizato** [comment]
<img width="1317" alt="スクリーンショット 2023-12-01 13 18 16" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/a4474a82-da1c-4a6a-bf63-2f6ea7c9bf16">

**Comment by SuzukaKuwabara** [comment]
@niizato 
ロゴマークの位置調整、修正いたしました。
※変わらない場合、リロードしてください。（Ctrl＋F5）

**Comment by niizato** [comment]
> @niizato ロゴマークの位置調整、修正いたしました。 ※変わらない場合、リロードしてください。（Ctrl＋F5）

確認しました！ありがとうございます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。一旦クローズしますね。
