### ISSUE TITLE
カテゴリーページ｜リンクぎれ

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#42]
eden　https://store.hasamiyaki.jp/shopbrand/eden/
空中庭園　https://store.hasamiyaki.jp/shopbrand/kutyuteien
terra　https://store.hasamiyaki.jp/shopbrand/terra/
boris tellegen　https://store.hasamiyaki.jp/shopbrand/boristellegen/

**Comment by SuzukaKuwabara** [comment]
@niizato 

こちらのリンク切れは対応完了いたしました！
