### ISSUE TITLE
デザイン確認｜　食器ジャーニー記事

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#5]
■ 食器ジャーニー記事
SP 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/332b36b5-e3ed-49b7-b9e5-0d786c2232f8
PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/41ffbed5-f203-44b2-b95b-22b621cfe647

**Comment by SuzukaKuwabara** [comment]
(さっき間違って違うissueに書き込んでしまったので再掲です)

@niizato 
確認を進めていただいているかと思いますが、１点お知らせです。

テキストの下線が途切れ途切れになっていますが、これはXDで作るとこうなってしまうだけで、実際に構築するとちゃんとした下線になりますのでご了承くださいm(_ _)m

<img width="330" alt="スクリーンショット 2023-09-04 11 41 39" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/9cf715c3-af0b-4319-89a5-a9837c537ed2">

**Comment by SuzukaKuwabara** [comment]
@niizato 
修正なしですので開発に進みます。
