### ISSUE TITLE
デザイン確認｜　すべての記事

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#6]
■ すべての記事
SP 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/2c9e5c3c-60f7-41d4-8aaf-9964a36feddb/
PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/aec56642-bdce-42d6-b8d8-7b8225a9e8de

**Comment by SuzukaKuwabara** [comment]
@niizato 
こちら修正指示ありませんでしたのでこのまま開発に進みますね。
