### ISSUE TITLE
デザイン確認｜　タグ一覧

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#7]
■ タグ一覧
SP 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/f0e77e09-4dc2-4e1b-81ee-2f2ce90d5f9f
PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/c58389fc-eadf-403f-bdc3-67f461c634f3

**Comment by SuzukaKuwabara** [comment]
@niizato 
修正しましたのでご確認お願いいたします！
スマホもPCも12px→14pxへ変更し、余白を調整しました。

SP 　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/f0e77e09-4dc2-4e1b-81ee-2f2ce90d5f9f
PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/screen/c58389fc-eadf-403f-bdc3-67f461c634f3

**Comment by niizato** [comment]
@SuzukaKuwabara ありがとうございます！どちらも問題ありません。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。では開発に進みます！

**Comment by SuzukaKuwabara** [comment]
@niizato 

### タグの件数について
タグ一覧ページに「件数」があるのですが、こちらは何の件数を想定されているでしょうか？
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/53a73b11-67a6-4f4a-8c3c-b30ab9ecef81" width="300">

というのも、技術的には
・全ての投稿数（記事一覧ページと同じということです） → 表示可能です
・登録されているタグの数 → 表示が難しそうです。
・タグがついている投稿数 → 表示が難しそうです。
という感じなので、もし「タグの数」などを想定されている場合は、実装がちょっと難しそうで・・・

**Comment by niizato** [comment]
@SuzukaKuwabara 

全ての投稿数で想定しています。

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。ではそちらで進めますね＾＾
