### ISSUE TITLE
フッターデザイン作成

### ISSUE THREAD

**Issue by niizato** [niizato/MARUHIRO-onlineshop-renewal#8]
全ページ共通のフッターを作成する。
項目を減らす。

**Comment by niizato** [comment]
@SuzukaKuwabara 

デザイン完了したのでご確認お願いします。


フッター
https://drive.google.com/file/d/1rYMPR3a0Y7PWcU6V3zp1hASFQXdd6mmG/view?usp=drive_link

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！アクセス権限がないようなので、
kuwabara@web-knots.com に権限を与えていただくなどしていただくか、
誰でもアクセスできるようにしていただいても良いでしょうか？

**Comment by niizato** [comment]
権限変更しました！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！確認しました。
こちらは今新しく作っている特集ページのWPでもいただいたデザインのフッターを使うということでしょうか・・・？

特集ページのフッターに関しては、下記とデザインは変わらず、掲載する内容のみが変わるとお伺いしていたと思うのですが・・・・
![スクリーンショット 2023-09-08 15 09 58](https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/d66052c4-4d20-4c1b-98a0-5f6b7937e7fe)

**Comment by niizato** [comment]
<img width="576" alt="スクリーンショット 2023-09-08 16 16 41" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/32931184-2b0b-46cc-96b2-0b3180a3b93d">

@SuzukaKuwabara 

今のフッターが見にくかったので、一列にして区切り線を入れるのは大丈夫かなーと思ってデザインしてみましたが手間がかかりますよね、、、
SNSのアイコンをフッターから取り除いて、2列にするデザインなら大丈夫ですか？

**Comment by niizato** [comment]
@SuzukaKuwabara 

まもなく退社で、次の出社が月曜になりますが大丈夫でしょうか？
返信だけなら明日もできます！

**Comment by SuzukaKuwabara** [comment]
@niizato 
遅くなってすみません；
タイムリーに通知が来なくって；；
（ちなみに余談ですがみなさんどうやって通知受け取ってますか・・・？メールの通知？）


変更するのであれば、どちらのデザインにするにしても修正時間に大差ないので、
昨日いただいたイラレ通りでも大丈夫ですよ＾＾

ご納得いただけるデザインで大丈夫ですので、また週明けにご指示ください。

**Comment by niizato** [comment]
> @niizato 遅くなってすみません； タイムリーに通知が来なくって；； （ちなみに余談ですがみなさんどうやって通知受け取ってますか・・・？メールの通知？）
> 
> 変更するのであれば、どちらのデザインにするにしても修正時間に大差ないので、 昨日いただいたイラレ通りでも大丈夫ですよ＾＾
> 
> ご納得いただけるデザインで大丈夫ですので、また週明けにご指示ください。


@SuzukaKuwabara 通知は私も来ないのでgithubをチラチラ見るか、メールで気づくかのどちらかです！

フッターの件すみません！修正時間大差ないのであれば当初のデザインでお願いします。

**Comment by niizato** [comment]
<img width="306" alt="スクリーンショット 2023-09-11 9 55 42" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/83c52784-0074-4d80-9e36-86ed05186401">

**Comment by SuzukaKuwabara** [comment]
@niizato 
承知しました。
では先日いただいたフッターのデザインで進めますね！

**Comment by SuzukaKuwabara** [comment]
@niizato 
フッターについてですが、
特集の記事ページでは、一番最後の方に「この記事をシェアしてね」のSNSアイコンがあるので
フッターのSNSアイコンとの距離感が近くなり、ちょっと違和感が出てしまいます。
<img src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/109566570/74561a31-39b0-4e70-bdf8-b9d47bb114ce" width="300">


構築側としては、**ECサイトとよみものサイトのフッターが同じでないといけない。ということはない**ので
よければフッター側のSNSアイコンの配置を変えてみてはどうかなと思いますが、
検討していただけないでしょうか？

ちなみに、「この特集のタグ」と「記事をシェアして感想を〜」の部分の位置を動かすのはおそらく難しいため、フッターでご調整いただけると幸いです。

実際にこちらから見てみてください
https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/screen/8d522149-f961-4cb3-b78c-2ae0e3219345/

**Comment by niizato** [comment]
@SuzukaKuwabara 
<img width="381" alt="スクリーンショット 2023-09-13 11 55 42" src="https://github.com/niizato/MARUHIRO-onlineshop-renewal/assets/21334300/bdeda1ca-d865-4924-9bd2-eaae5b5cf32a">

確かによみものでは変になってしまうので、SNSのアイコンを少し小さくして一番下に置きました。
ECサイトもよみものも共通のデザインにしようかと思います。

▼修正版
https://drive.google.com/file/d/1Xniz0SbFe0Pd7z_l-Z2KBN-dWq9AZQnu/view?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます！
こちらで調整して、SPもPCももう一回ご確認いただきますね。

**Comment by SuzukaKuwabara** [comment]
@niizato 

### フッターご確認お願いいたします

■ SP　https://xd.adobe.com/view/d6719fd7-6af0-4931-9577-1ad5d827d22b-8322/
■ PC　https://xd.adobe.com/view/6a7c7058-40c5-4253-a3e8-3198a1751479-3f2f/

文字のサイズは、デザインデータ合わせではなく、以前のデザインの時にご指摘があったため、大きめにしていますがどうでしょうか？

ご確認お願いします！

**Comment by niizato** [comment]
@SuzukaKuwabara 

問題ありません！

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます＾＾
ではこちらで進めます！
